/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caneta;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class menu extends javax.swing.JFrame {
    Caneta caneta = new Caneta();
    ArrayList<Caneta> canetas = new ArrayList();
    DefaultComboBoxModel modelo;

    public menu() {
        initComponents();
        grupo.add(ponta1);
        grupo.add(ponta2);
        grupo.add(ponta3);
        grupo.add(ponta4);
        
        grupoCor.add(corAzul);
        grupoCor.add(corVerde);
        grupoCor.add(corVermelha);
        grupoCor.add(corPreta);
        
        grupoTampa.add(radioTampada);
        grupoTampa.add(radioDestampada);
        
      modelo = (DefaultComboBoxModel) cbCaneta.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        grupoCor = new javax.swing.ButtonGroup();
        grupoTampa = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        labelModelo = new javax.swing.JLabel();
        modeloText = new javax.swing.JTextField();
        corAzul = new javax.swing.JRadioButton();
        corPreta = new javax.swing.JRadioButton();
        corVermelha = new javax.swing.JRadioButton();
        corVerde = new javax.swing.JRadioButton();
        labelCor = new javax.swing.JLabel();
        labelPonta = new javax.swing.JLabel();
        radioTampada = new javax.swing.JRadioButton();
        radioDestampada = new javax.swing.JRadioButton();
        ponta1 = new javax.swing.JRadioButton();
        ponta2 = new javax.swing.JRadioButton();
        ponta3 = new javax.swing.JRadioButton();
        ponta4 = new javax.swing.JRadioButton();
        labelCarga = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnExibir = new javax.swing.JButton();
        btnTampar = new javax.swing.JButton();
        btnDestampar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        slideCarga = new javax.swing.JSlider();
        cbCaneta = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu da caneta");
        setLocation(new java.awt.Point(300, 300));
        setResizable(false);

        labelModelo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelModelo.setText("Modelo:");

        modeloText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloTextActionPerformed(evt);
            }
        });

        grupoCor.add(corAzul);
        corAzul.setText("Azul");
        corAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corAzulActionPerformed(evt);
            }
        });

        grupoCor.add(corPreta);
        corPreta.setText("Preta");
        corPreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corPretaActionPerformed(evt);
            }
        });

        grupoCor.add(corVermelha);
        corVermelha.setText("Vermelha");
        corVermelha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corVermelhaActionPerformed(evt);
            }
        });

        grupoCor.add(corVerde);
        corVerde.setText("Verde");
        corVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corVerdeActionPerformed(evt);
            }
        });

        labelCor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelCor.setText("Cor:");

        labelPonta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelPonta.setText("Ponta:");

        radioTampada.setText("Tampada");
        radioTampada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTampadaActionPerformed(evt);
            }
        });

        radioDestampada.setText("Destampada");
        radioDestampada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDestampadaActionPerformed(evt);
            }
        });

        ponta1.setText("0.7");
        ponta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponta1ActionPerformed(evt);
            }
        });

        ponta2.setText("1");

        ponta3.setText("1.4");
        ponta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponta3ActionPerformed(evt);
            }
        });

        ponta4.setText("1.6");
        ponta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponta4ActionPerformed(evt);
            }
        });

        labelCarga.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelCarga.setText("Carga:");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnExibir.setText("Exibir");
        btnExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirActionPerformed(evt);
            }
        });

        btnTampar.setText("Tampar");
        btnTampar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTampar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamparActionPerformed(evt);
            }
        });

        btnDestampar.setText("Destampar");
        btnDestampar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDestampar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestamparActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Estado:");

        slideCarga.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slideCargaStateChanged(evt);
            }
        });

        cbCaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCanetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modeloText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(radioTampada)
                                .addGap(18, 18, 18)
                                .addComponent(radioDestampada))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPonta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ponta1)
                                .addGap(18, 18, 18)
                                .addComponent(ponta2)
                                .addGap(18, 18, 18)
                                .addComponent(ponta3)
                                .addGap(18, 18, 18)
                                .addComponent(ponta4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corAzul)
                                .addGap(18, 18, 18)
                                .addComponent(corVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(corVermelha, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(corPreta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTampar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(btnDestampar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(slideCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbCaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeloText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCor)
                    .addComponent(corAzul)
                    .addComponent(corVerde)
                    .addComponent(corVermelha)
                    .addComponent(corPreta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPonta)
                    .addComponent(ponta1)
                    .addComponent(ponta2)
                    .addComponent(ponta3)
                    .addComponent(ponta4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCarga)
                    .addComponent(slideCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTampada)
                    .addComponent(radioDestampada)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExibir)
                    .addComponent(btnTampar)
                    .addComponent(btnCadastrar)
                    .addComponent(btnSair)
                    .addComponent(btnDestampar))
                .addGap(36, 36, 36)
                .addComponent(cbCaneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modeloTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloTextActionPerformed

    private void corAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corAzulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corAzulActionPerformed

    private void corVermelhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corVermelhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corVermelhaActionPerformed

    private void corVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corVerdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corVerdeActionPerformed

    private void radioTampadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTampadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTampadaActionPerformed

    private void radioDestampadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDestampadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDestampadaActionPerformed

    private void ponta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponta3ActionPerformed

    private void corPretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corPretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corPretaActionPerformed

    private void ponta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponta4ActionPerformed

    private void btnExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirActionPerformed
        // TODO add your handling code here
        JOptionPane.showConfirmDialog(this, caneta);
    }//GEN-LAST:event_btnExibirActionPerformed

    private void btnTamparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamparActionPerformed
        // TODO add your handling code here:
        radioTampada.setSelected(true);
    }//GEN-LAST:event_btnTamparActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        String modeloCaneta = caneta.modelo = modeloText.getText(); 
        String cor = null;
        float ponta = 0;
        int carga = 0;
        String estado = null;
        
        if(corAzul.isSelected()){
            caneta.cor = corAzul.getText();
            cor = caneta.cor;
        }else  if(corVerde.isSelected()){
            caneta.cor = corVerde.getText();
            cor= caneta.cor;
        }else  if(corVermelha.isSelected()){
            caneta.cor = corVermelha.getText();
            cor= caneta.cor;
        }else  if(corPreta.isSelected()){
            caneta.cor = corPreta.getText();
            cor = caneta.cor;
       }
        
         if(ponta1.isSelected()){
           caneta.ponta =   Float.parseFloat(ponta1.getText());
           ponta = caneta.ponta;
         }else if(ponta2.isSelected()){
             caneta.ponta  = Float.parseFloat(ponta2.getText());
             ponta = caneta.ponta;
         }else if(ponta3.isSelected()){
             caneta.ponta  = Float.parseFloat(ponta3.getText());
             ponta = caneta.ponta;
         }else if(ponta4.isSelected()){
             caneta.ponta = Float.parseFloat(ponta4.getText());
             ponta = caneta.ponta;
         }
         
         caneta.carga = slideCarga.getValue();
         carga =caneta.carga;

         if(radioTampada.isSelected()){
             caneta.tampada = true;
               estado = "TAMPADA!!";
         }else if(radioDestampada.isSelected()){
             caneta.tampada = true;
             estado  = "DESTAMPADA!!";
         }
         
         JOptionPane.showConfirmDialog(this, "Você acaba de cadastrar a caneta com as seguintes caracteristicas:\n"
                 + "Modelo:"+modeloCaneta+"\n"
                 + "Cor:"+cor+"\n"
                 + "Ponta:"+ponta+"\n"
                 + "Carga:"+carga+"%\n"
                 + "Estado:"+estado);
         
         canetas.add(caneta);
         this.modelo.addElement(caneta);
          caneta = new Caneta();
         
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnDestamparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestamparActionPerformed
        // TODO add your handling code here:
        radioDestampada.setSelected(true);
    }//GEN-LAST:event_btnDestamparActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void ponta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponta1ActionPerformed

    private void slideCargaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slideCargaStateChanged
        // TODO add your handling code here:
        caneta.carga = slideCarga.getValue();
    }//GEN-LAST:event_slideCargaStateChanged

    private void cbCanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCanetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCanetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDestampar;
    private javax.swing.JButton btnExibir;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTampar;
    private javax.swing.JComboBox<String> cbCaneta;
    private javax.swing.JRadioButton corAzul;
    private javax.swing.JRadioButton corPreta;
    private javax.swing.JRadioButton corVerde;
    private javax.swing.JRadioButton corVermelha;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.ButtonGroup grupoCor;
    private javax.swing.ButtonGroup grupoTampa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCarga;
    private javax.swing.JLabel labelCor;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelPonta;
    private javax.swing.JTextField modeloText;
    private javax.swing.JRadioButton ponta1;
    private javax.swing.JRadioButton ponta2;
    private javax.swing.JRadioButton ponta3;
    private javax.swing.JRadioButton ponta4;
    private javax.swing.JRadioButton radioDestampada;
    private javax.swing.JRadioButton radioTampada;
    private javax.swing.JSlider slideCarga;
    // End of variables declaration//GEN-END:variables
}
